id: IC12FF5FC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:18:45+00:00'
last_modified: '2022-06-07T12:38:32.805328+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3391
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2102':
      image_group_id: I1KG3458
      title: ''
      total_pages: 1590
      order: 1
      base_file: 2102.txt
    '8234':
      image_group_id: I1KG3459
      title: ''
      total_pages: 1252
      order: 2
      base_file: 8234.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
