id: IC12FF5FC
legacy_id: P000678
ocr_import_info:
  bdrc_scan_id: W1KG3391
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T15:10:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:57:37.364137+00:00'
last_modified: 2022-08-31 22:58:37.116924
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3391
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3391
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ།
  author: དཾ་ཥྚཱ་སེ་ན།
statistics:
  ocr_word_mean_confidence_index: 0.8818815242813904
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG3459:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3459
      total_pages: 1252
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG3459.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8797880201025773
    legacy_id: v002
  I1KG3458:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3458
      total_pages: 1590
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3458.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8834745018555907
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
